"use client"
import "@styles/globals.css"
import Nav from "@components/Nav"
import { MyProvider } from "@/context";
import { useEffect } from "react";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import { Open_Sans } from "next/font/google"

const openSans = Open_Sans({
  weight: '400',
  style: 'normal',
  subsets: ['latin']
})


export default function RootLayout({ children }) {
  useEffect(() => {
    const canvas = document.getElementById('bgCanvas');
  const ctx = canvas.getContext('2d');

  function resizeCanvas() {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    drawBubbles();
  }

  function drawBubbles() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    for (let i = 0; i < 6; i++) {
      const x = Math.random() * canvas.width * 0.9 + canvas.width * 0.05;
      const y = Math.random() * canvas.height * 0.9 + canvas.height * 0.05;
      const r = Math.random() * 100 + 60; // Bigger bubbles

      console.log("Circle", i, "X:", x, "Y:", y, "R:", r);
      ctx.beginPath();
      ctx.arc(x, y, r, 0, 2 * Math.PI);
      ctx.fillStyle = `rgba(56, 189, 248, ${Math.random() * 0.3 + 0.4})`; // Sky-blue with 0.4–0.7 opacity
      ctx.fill();
    }
  }

  // Init
  window.addEventListener('resize', resizeCanvas);
  resizeCanvas();

  },[])

  return (
    <html lang="en" className={openSans.className}>
      <body>

        <MyProvider>
          <Nav />
        <canvas id="bgCanvas"  className="h-[100%] w-[100%] fixed top-0 left-0 z-[-20]">
        </canvas>
          {children}
        </MyProvider>
      </body>
    </html>
  )
}
