import "@styles/globals.css" 
import Nav from "@components/Nav"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Open_Sans } from "next/font/google"

const openSans = Open_Sans({
  weight: '400',
  style: 'normal',
  subsets: ['latin']
 })

export default function RootLayout({ children }) {
 return (
    <html lang="en" className={openSans.className}>
      <body>
        <Nav/>
        {children}
      </body>
    </html>
  )
}
